name: PeriodicAnnounce
version: ${project.version}
main: com.nekozouneko.periodicAnnounce.PeriodicAnnounce
api-version: '1.21'
folia-supported: true
description: 定期的にメッセージを流すだけのプラグイン
author: RunQ

commands:
  pannounce:
    aliases: [ periodannounce ]
    description: "PeriodAnnounceのメインコマンド"
    usage: "/<command>"
    permission: periodannounce

permissions:
  periodannounce:
    default: op